"""add missing fields

Revision ID: 14fb705cdeb7
Revises: 98cb03ea16ad
Create Date: 2025-05-14 23:58:25.227649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14fb705cdeb7'
down_revision = '98cb03ea16ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.drop_column('register_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('last_login')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
