"""Create User and Patient tables

Revision ID: 4bf4b55b2021
Revises: 
Create Date: 2025-05-02 04:27:57.837645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf4b55b2021'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('specialty', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('education', sa.String(length=200), nullable=True),
    sa.Column('experience', sa.String(length=300), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=200), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('sw_id', sa.Integer(), nullable=True),
    sa.Column('psych_id', sa.Integer(), nullable=True),
    sa.Column('physio_id', sa.Integer(), nullable=True),
    sa.Column('ot_id', sa.Integer(), nullable=True),
    sa.Column('medical_info', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ot_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['physio_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['psych_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sw_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    op.drop_table('user')
    # ### end Alembic commands ###
