"""Temp migration in feature branch

Revision ID: 8883e432d8be
Revises: 
Create Date: 2025-05-12 00:10:21.832135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8883e432d8be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_date', sa.Date(), nullable=False))
        batch_op.drop_column('submitted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('report_date')

    # ### end Alembic commands ###
