"""Remove avatar_url from User model

Revision ID: 8a9687843acd
Revises: d4876b9c8f0f
Create Date: 2025-05-14 19:56:31.238575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9687843acd'
down_revision = 'd4876b9c8f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
