"""Initial migration for full model structure

Revision ID: 9905d6e5eed6
Revises: 
Create Date: 2025-05-12 23:34:45.428828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9905d6e5eed6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('specialty', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('education', sa.String(length=200), nullable=True),
    sa.Column('experience', sa.String(length=300), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=200), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('sw_id', sa.Integer(), nullable=True),
    sa.Column('psych_id', sa.Integer(), nullable=True),
    sa.Column('physio_id', sa.Integer(), nullable=True),
    sa.Column('ot_id', sa.Integer(), nullable=True),
    sa.Column('medical_info', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ot_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['physio_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['psych_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sw_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_worker_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('q1_emotion_stable', sa.String(length=10), nullable=True),
    sa.Column('q2_pain_present', sa.String(length=10), nullable=True),
    sa.Column('q3_energy_level', sa.Integer(), nullable=True),
    sa.Column('q4_food_intake', sa.String(length=20), nullable=True),
    sa.Column('q5_daily_activities', sa.String(length=10), nullable=True),
    sa.Column('q6_physical_training', sa.Integer(), nullable=True),
    sa.Column('q7_post_exercise_pain', sa.Integer(), nullable=True),
    sa.Column('q8_balance_score', sa.Integer(), nullable=True),
    sa.Column('q9_self_care', sa.Integer(), nullable=True),
    sa.Column('q10_household_tasks', sa.String(length=30), nullable=True),
    sa.Column('q11_skill_learning', sa.String(length=10), nullable=True),
    sa.Column('q12_emotional_fluctuations', sa.Integer(), nullable=True),
    sa.Column('q13_social_willingness', sa.Integer(), nullable=True),
    sa.Column('q14_therapist_response', sa.Integer(), nullable=True),
    sa.Column('q15_anxiety_depression', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['support_worker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('share_with_guardian', sa.Boolean(), nullable=True),
    sa.Column('share_with_sw', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_plan')
    op.drop_table('questionnaire_answer')
    op.drop_table('patient')
    op.drop_table('user')
    # ### end Alembic commands ###
