"""Second try - add QuestionnaireAnswer table

Revision ID: c47c6cc34e53
Revises: 4bf4b55b2021
Create Date: 2025-05-05 22:29:49.117617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47c6cc34e53'
down_revision = '4bf4b55b2021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_worker_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('q1_emotion_stable', sa.String(length=10), nullable=True),
    sa.Column('q2_pain_present', sa.String(length=10), nullable=True),
    sa.Column('q3_energy_level', sa.Integer(), nullable=True),
    sa.Column('q4_food_intake', sa.String(length=20), nullable=True),
    sa.Column('q5_daily_activities', sa.String(length=10), nullable=True),
    sa.Column('q6_training_completion', sa.Integer(), nullable=True),
    sa.Column('q7_pain_score', sa.Integer(), nullable=True),
    sa.Column('q8_balance_ability', sa.Integer(), nullable=True),
    sa.Column('q9_selfcare_willingness', sa.Integer(), nullable=True),
    sa.Column('q10_household_tasks', sa.String(length=30), nullable=True),
    sa.Column('q11_skill_learning', sa.String(length=10), nullable=True),
    sa.Column('q12_emotion_fluctuations', sa.Integer(), nullable=True),
    sa.Column('q13_social_willingness', sa.Integer(), nullable=True),
    sa.Column('q14_therapist_responsiveness', sa.Integer(), nullable=True),
    sa.Column('q15_anxiety_signs', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['support_worker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionnaire_answer')
    # ### end Alembic commands ###
