"""Rename last_login to register_time

Revision ID: d4876b9c8f0f
Revises: 9905d6e5eed6
Create Date: 2025-05-14 19:52:15.020132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4876b9c8f0f'
down_revision = '9905d6e5eed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DATETIME(), nullable=True))
        batch_op.drop_column('register_time')

    # ### end Alembic commands ###
